config/routes.rb
Architastic::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :crit_requirements

  resources :crit_notes

  resources :crits

  resources :todos

  resources :tasks

  resources :briefs

  resources :projects

  root :to => "home#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :briefs
  has_many :tasks
  has_one :crit
  
  # NOT YET DEFINED __ belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.xml
  def index
    @projects = Project.all
    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.xml
  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.xml
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.xml
  def create
    @project = Project.new(params[:project])
    
    respond_to do |format|
      if @project.save
        flash[:message] ="Project successfully created."
        format.html { redirect_to :controller => "home", :action => "index" }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
    
  end

  # PUT /projects/1
  # PUT /projects/1.xml
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.xml
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      flash[:message] ="Project successfully deleted"
      format.html { redirect_to :controller => "home", :action => "index" }
      format.xml  { head :ok }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Deadline</th>
    <th>Status</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.id %></td>
    <td><%= project.name %></td>
    <td><%= project.deadline %></td>
    <td><%= project.status %></td>
    <td><%= project.user_id %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to "Back to Your Projects", :controller => "home", :action => "index" %>

<p>
  <b>Project:</b>
  <%= @project.name %>
</p>

<p>
  <b>Deadline:</b>
  <%= @project.deadline %>
</p>

<p>
  <b>Status:</b>
  <%= @project.status %>
</p>

<hr />
<h2>Tasks remaining</h2>
<% @tasks.each do |task| %>
	<dt><strong>Task Name: <%= task.name %><br /></strong></dt><br />
	<dt><strong>Priority: <%= task.priority %><br /></strong></dt>
	<br />
	<%= link_to 'Destroy', task, :method => :delete %>
<% end %>
<hr />
<h1>Add new task</h1>

<%= form_for :task, @task, :url => {:controller => "tasks", :action => "create"}, :html => {:class => "add_task_form"} do |f| %>

	<label for="name">Name:</label>
	<p><%= f.text_field :name %></p>
	
	<label for="deadline">Priority:</label>
	<p><%= select 'task', 'priority', %w(Low Medium High) %></p>
	
	<%= f.hidden_field :status, :value => "Active" %>
	
	<%= f.hidden_field :project_id, :value => @project.id %>
	
	<%= submit_tag 'Add Task' %>
	
<% end %>

<!--
<%= link_to 'Edit', edit_project_path(@project) %> 
<%= link_to 'Back', projects_path %>
-->