config/routes.rb
Architastic::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :crit_requirements

  resources :crit_notes

  resources :crits

  resources :todos

  resources :tasks

  resources :briefs

  resources :projects

  root :to => "home#index"

end

app/models/brief.rb
class Brief < ActiveRecord::Base
  belongs_to :project
end

app/controllers/briefs_controller.rb
class BriefsController < ApplicationController
  # GET /briefs
  # GET /briefs.xml
  def index
    @briefs = Brief.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @briefs }
    end
  end

  # GET /briefs/1
  # GET /briefs/1.xml
  def show
    @brief = Brief.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @brief }
    end
  end

  # GET /briefs/new
  # GET /briefs/new.xml
  def new
    @brief = Brief.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @brief }
    end
  end

  # GET /briefs/1/edit
  def edit
    @brief = Brief.find(params[:id])
  end

  # POST /briefs
  # POST /briefs.xml
  def create
    @brief = Brief.new(params[:brief])

    respond_to do |format|
      if @brief.save
        format.html { redirect_to(@brief, :notice => 'Brief was successfully created.') }
        format.xml  { render :xml => @brief, :status => :created, :location => @brief }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @brief.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /briefs/1
  # PUT /briefs/1.xml
  def update
    @brief = Brief.find(params[:id])

    respond_to do |format|
      if @brief.update_attributes(params[:brief])
        format.html { redirect_to(@brief, :notice => 'Brief was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @brief.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /briefs/1
  # DELETE /briefs/1.xml
  def destroy
    @brief = Brief.find(params[:id])
    @brief.destroy

    respond_to do |format|
      format.html { redirect_to(briefs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/briefs_helper.rb
module BriefsHelper
end

app/views/briefs/_form.html.erb
<%= form_for(@brief) do |f| %>
  <% if @brief.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brief.errors.count, "error") %> prohibited this brief from being saved:</h2>

      <ul>
      <% @brief.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :file_url %><br />
    <%= f.text_field :file_url %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.text_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/briefs/edit.html.erb
<h1>Editing brief</h1>

<%= render 'form' %>

<%= link_to 'Show', @brief %> |
<%= link_to 'Back', briefs_path %>

app/views/briefs/index.html.erb
<h1>Listing briefs</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>File url</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @briefs.each do |brief| %>
  <tr>
    <td><%= brief.id %></td>
    <td><%= brief.name %></td>
    <td><%= brief.file_url %></td>
    <td><%= brief.project_id %></td>
    <td><%= link_to 'Show', brief %></td>
    <td><%= link_to 'Edit', edit_brief_path(brief) %></td>
    <td><%= link_to 'Destroy', brief, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brief', new_brief_path %>

app/views/briefs/new.html.erb
<h1>New brief</h1>

<%= render 'form' %>

<%= link_to 'Back', briefs_path %>

app/views/briefs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @brief.id %>
</p>

<p>
  <b>Name:</b>
  <%= @brief.name %>
</p>

<p>
  <b>File url:</b>
  <%= @brief.file_url %>
</p>

<p>
  <b>Project:</b>
  <%= @brief.project_id %>
</p>


<%= link_to 'Edit', edit_brief_path(@brief) %> |
<%= link_to 'Back', briefs_path %>