config/routes.rb
Architastic::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :crit_requirements

  resources :crit_notes

  resources :crits

  resources :todos

  resources :tasks

  resources :briefs

  resources :projects

  root :to => "home#index"

end

app/models/crit_requirement.rb
class CritRequirement < ActiveRecord::Base
  belongs_to :crit
end

app/controllers/crit_requirements_controller.rb
class CritRequirementsController < ApplicationController
  # GET /crit_requirements
  # GET /crit_requirements.xml
  def index
    @crit_requirements = CritRequirement.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @crit_requirements }
    end
  end

  # GET /crit_requirements/1
  # GET /crit_requirements/1.xml
  def show
    @crit_requirement = CritRequirement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @crit_requirement }
    end
  end

  # GET /crit_requirements/new
  # GET /crit_requirements/new.xml
  def new
    @crit_requirement = CritRequirement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @crit_requirement }
    end
  end

  # GET /crit_requirements/1/edit
  def edit
    @crit_requirement = CritRequirement.find(params[:id])
  end

  # POST /crit_requirements
  # POST /crit_requirements.xml
  def create
    @crit_requirement = CritRequirement.new(params[:crit_requirement])

    respond_to do |format|
      if @crit_requirement.save
        format.html { redirect_to(@crit_requirement, :notice => 'Crit requirement was successfully created.') }
        format.xml  { render :xml => @crit_requirement, :status => :created, :location => @crit_requirement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @crit_requirement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /crit_requirements/1
  # PUT /crit_requirements/1.xml
  def update
    @crit_requirement = CritRequirement.find(params[:id])

    respond_to do |format|
      if @crit_requirement.update_attributes(params[:crit_requirement])
        format.html { redirect_to(@crit_requirement, :notice => 'Crit requirement was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @crit_requirement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /crit_requirements/1
  # DELETE /crit_requirements/1.xml
  def destroy
    @crit_requirement = CritRequirement.find(params[:id])
    @crit_requirement.destroy

    respond_to do |format|
      format.html { redirect_to(crit_requirements_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/crit_requirements_helper.rb
module CritRequirementsHelper
end

app/views/crit_requirements/_form.html.erb
<%= form_for(@crit_requirement) do |f| %>
  <% if @crit_requirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crit_requirement.errors.count, "error") %> prohibited this crit_requirement from being saved:</h2>

      <ul>
      <% @crit_requirement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :crit_id %><br />
    <%= f.text_field :crit_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/crit_requirements/edit.html.erb
<h1>Editing crit_requirement</h1>

<%= render 'form' %>

<%= link_to 'Show', @crit_requirement %> |
<%= link_to 'Back', crit_requirements_path %>

app/views/crit_requirements/index.html.erb
<h1>Listing crit_requirements</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Status</th>
    <th>Crit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @crit_requirements.each do |crit_requirement| %>
  <tr>
    <td><%= crit_requirement.id %></td>
    <td><%= crit_requirement.name %></td>
    <td><%= crit_requirement.status %></td>
    <td><%= crit_requirement.crit_id %></td>
    <td><%= link_to 'Show', crit_requirement %></td>
    <td><%= link_to 'Edit', edit_crit_requirement_path(crit_requirement) %></td>
    <td><%= link_to 'Destroy', crit_requirement, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Crit requirement', new_crit_requirement_path %>

app/views/crit_requirements/new.html.erb
<h1>New crit_requirement</h1>

<%= render 'form' %>

<%= link_to 'Back', crit_requirements_path %>

app/views/crit_requirements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @crit_requirement.id %>
</p>

<p>
  <b>Name:</b>
  <%= @crit_requirement.name %>
</p>

<p>
  <b>Status:</b>
  <%= @crit_requirement.status %>
</p>

<p>
  <b>Crit:</b>
  <%= @crit_requirement.crit_id %>
</p>


<%= link_to 'Edit', edit_crit_requirement_path(@crit_requirement) %> |
<%= link_to 'Back', crit_requirements_path %>